% --- Funcion Main
function script_03_01
    interfazGrafica()
end

% --- Funcion Front-end
function interfazGrafica()
% Funcion Front-end.

    d = dialog('Position',[300 300 790 150],'Name','Base de datos de materias');
    
    textMsj = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[150 15 300 25],...
               'String','Materia ingresado correctamente ...',...
               'ForegroundColor', [0 0.5 0],...
               'Visible','off');
    
    textMateria = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 100 100 30],...
               'String','Materia');
     
    edit.Materia = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[20 80 100 30],...
               'String','Señales y sistemas');
           
    textFecha = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[150 100 100 30],...
               'String','Fecha de cursada');
    
    textFecha1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[175 90 10 10],...
               'String','/');
           
    textFecha2 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[215 90 10 10],...
               'String','/');
           
    edit.Fecha1 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[150 80 20 30],...
               'String','10');
    
    edit.Fecha2 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[190 80 20 30],...
               'String','03');
           
    edit.Fecha3 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[230 80 20 30],...
               'String','17');
           
    textDocentes = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[280 110 100 30],...
               'String','Docentes de la asignatura');
    
    edit.Docentes = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[280 80 100 30],...
               'String','Gonzales M., Fernandez F.');
           
    textExamen_1 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[410 100 100 30],...
               'String','Examen N�1');
    
    edit.Examen_1 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[410 80 100 30],...
               'String','70');
    
    textExamen_2 = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[540 100 100 30],...
               'String','Examen N�2');
           
    edit.Examen_2 = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[540 80 100 30],...
               'String','80');
           
    textoExamenFinal = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[670 100 100 30],...
               'String','Examen Final');
    
    edit.ExamenFinal = uicontrol('Parent',d,...
               'Style','edit',...
               'Position',[670 80 100 30],...
               'String','50');

    btnCerrar = uicontrol('Parent',d,...
               'Position',[700 20 70 25],...
               'String','Cerrar',...
               'Callback','delete(gcf)');
           
    btn = uicontrol('Parent',d,...
               'Position',[20 20 70 25],...
               'String','Ingresar',...
               'Callback',{@ingresar,edit,textMsj});
           
    btn = uicontrol('Parent',d,...
               'Position',[110 20 70 25],...
               'String','Consultar',...
               'Callback',@consultar);
end

% --- Funciones Back-end
function ingresar(~,~,edit,textMsj)
      
        materia = {edit.Materia.String};
        fecha = [str2double(edit.Fecha3.String) str2double(edit.Fecha2.String) str2double(edit.Fecha1.String)]; 
        docentes = {edit.Docentes.String};
        examen_1 = str2double(edit.Examen_1.String);
        examen_2 = str2double(edit.Examen_2.String);
        examenFinal = str2double(edit.ExamenFinal.String);
        
        prom = promedio ([examen_1 examen_2 examenFinal]); % funcion externa
        
        T = table(materia, fecha, docentes, examen_1, examen_2, examenFinal,prom);
        
        writetable(T,'materiasUNTREF.txt','Delimiter',' ');


        edit.Materia.String = '';
        edit.Fecha1.String = '';
        edit.Fecha2.String = '';
        edit.Fecha3.String = '';
        edit.Docentes.String = '';
        edit.Examen_1.String = '';
        edit.Examen_2.String = '';
        edit.ExamenFinal.String = '';
        textMsj.Visible = 'on';
        pause (3)
        textMsj.Visible = 'off';
        
end
    
function consultar(~,~)
         
        f = figure('Name','Consulta de base de datos','NumberTitle','off','WindowStyle','modal','Position',[300 300 825 250]);
        aux = readtable('materiasUNTREF.txt');
        aux1 = table2cell(aux);
        
        cnames = {'Materia','Dia','Mes','A�o','Docentes de la asignatura','Examen N�1','Examen N�2','Examen Final','Promedio'};
        
        t = uitable(f,'Data',aux1,'ColumnName',cnames);
        
        % Configurar el ancho y alto de las celdas
        t.Position(3) = t.Extent(3);
        t.Position(4) = t.Extent(4);
end