function script12 ()
% script12 () 
%
% Función que resuelve el ejercicio 1 de la guia 4
%
% Marzo, 2017

    clc
    clear all

    t_final = 20; fs = 1000;
    t = 0:1/fs:t_final;   
    f = 1;
    xt = 2*cos(2*pi*f*t/12);
    
    d_aux = [zeros(1,1000) 1]; % Con desplazamiento de 1s 
    dis = length(xt)-length(d_aux);
    d = [d_aux zeros(1,dis)];
%     d = [1 zeros(1,10)];   % Sin desplazamiento.
    y = conv(xt,d);
    
% Ploteo de los resultados
    scrsz = get(groot,'ScreenSize');
    figure1 = figure('Name','Ejercicio 1 de la guia 4','NumberTitle','off','WindowStyle','modal');
    set(figure1,'Position',[scrsz(3)/4 scrsz(4)/4 scrsz(3)/2 scrsz(4)/2]);   % [left bottom width height]
    
    subplot(3,1,1,'Parent',figure1)
    resultado (t,xt)
    axis([0 t(end) -3 3])
    set(gca,...
        'Units','normalized',...
        'YTick',-3:1:3,...
        'XTick',0:t(end)/20:t(end),...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',10,...
        'FontName','Times')
    ylabel({'$x(t)$'})
    xlabel('Tiempo(s)')
    legend({'$x=2\cos(2\pi ft/12)$'},'interpreter','latex')
    title('Función cosenoidal')
      
    subplot(3,1,2,'Parent',figure1)
    resultado (t,d)
    axis([0 t(end) -3 3])
    set(gca,...
        'Units','normalized',...
        'YTick',-3:1:3,...
        'XTick',0:t(end)/20:t(end),...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',10,...
        'FontName','Times')
    ylabel({'$x(t)$'})
    xlabel('Tiempo(s)')
    legend({'$x=2\cos(2\pi ft/12)$'},'interpreter','latex')
    title('Función cosenoidal')

end  

function resultado (x,y)
    
    plot(x,y); 
  
    ylabel({''},...
            'FontUnits','points',...
            'interpreter','latex',...
            'FontSize',10,...
            'FontName','Times')

    xlabel('',...
           'FontUnits','points',...
           'FontWeight','normal',...
           'FontSize',10,...
           'FontName','Times')

    legend('',...
            'FontUnits','points',...
            'interpreter','latex',...
            'FontSize',10,...
            'FontName','Times',...
            'Location','NorthEast')
        
    title('',...
          'FontUnits','points',...
          'FontWeight','normal',...
          'FontSize',10,...
          'FontName','Times')
      
    grid on
end